### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by suttapong-secured**
display overflow with `

### CODE REVIEW

**Comment by bkimminich** [comment]
I don't get the point of this change to use https://www.markdownguide.org/basic-syntax/#escaping-backticks. Can you please show the effect this is supposed to have on the rendered HTML or exported PDF?

**Comment by suttapong-secured** [comment]
both web and pdf has overflow problem
image
image
only "Bonus Payload" row use 1tick while others use 3ticks
its wont wrap code block like 3ticks (other code block use 3ticks)
compare to html while remove "Bonus Payload" row which display hint and solution column
image

**Comment by bkimminich** [comment]
I can check if a triple backtick will solve this, I was just confused how the double tick you submitted would impact rendering, as I thought this is just escaping the backtick in Markdown. I'll try it out, though.

**Comment by suttapong-secured** [comment]
sorry my bad, its 2ticks to solve display issue, like other code block use

**Comment by bkimminich** [comment]
With two or three backticks the rendering issue just remains the same. Tested in Chrome and Edge.

**Pull request closed without merging**
